_wandb:
    value:
        cli_version: 0.18.6
        m: []
        python_version: 3.12.7
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 13
                - 16
                - 23
                - 55
            "4": 3.12.7
            "5": 0.18.6
            "8":
                - 5
            "12": 0.18.6
            "13": darwin-arm64
algorithm:
    value: PPO
batch_size:
    value: 128
clip_range:
    value: 0.2
ent_coef:
    value: 0.01
learning_rate:
    value: 0.0001
n_envs:
    value: 8
n_epochs:
    value: 10
n_steps:
    value: 2048
total_timesteps:
    value: 100000
