# 实验设置
exp_name: "ppo_grasp_1d_v1"
project_name: "grasp-rl-1d"
n_envs: 1

# 环境参数
reward_scale: 1.0
max_episodes: 1000
eval_interval: 100
initial_exploration_rate: 0.99

# 训练参数
eval_freq: 1000
n_eval_episodes: 5
save_freq: 10000
learning_rate: 1.0e-4
n_steps: 2048
batch_size: 128
n_epochs: 10
gamma: 0.99
clip_range: 0.2
ent_coef: 0.01
total_timesteps: 100000

# 环境配置
environment:
  env_module: "tactile_envs.envs"
  env_class: "RLGraspEnv1D"
  env_kwargs:
    no_rotation: true
    no_gripping: false
    state_type: "vision_and_touch"
    camera_idx: 0
    symlog_tactile: true
    im_size: 480
    tactile_shape: [20, 20]
    skip_frame: 5
    # render_mode: "human" 